// 이미지 로딩 중 표시할 그레이 플레이스홀더 (8×8 #E5E5E5 PNG)
export const GRAY_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAD0lEQVR4nGN4igMwDC0JABu1q8HC71HKAAAAAElFTkSuQmCC";
